export const ACCENTS = [
  { id: "colombian", name: "Colombiano", country: "Colombia", flag: "https://flagcdn.com/w40/co.png", color: "#FFD700", locale: "es-CO", voice: "es-CO-SalomeNeural", description: "Acento colombiano" },
  { id: "argentinian", name: "Argentino", country: "Argentina", flag: "https://flagcdn.com/w40/ar.png", color: "#74ACDF", locale: "es-AR", voice: "es-AR-TomasNeural", description: "Acento porteño rioplatense" },
  { id: "mexican", name: "Mexicano", country: "México", flag: "https://flagcdn.com/w40/mx.png", color: "#006847", locale: "es-MX", voice: "es-MX-DaliaNeural", description: "Acento mexicano" },
  { id: "spanish", name: "Español (España)", country: "España", flag: "https://flagcdn.com/w40/es.png", color: "#c60b1e", locale: "es-ES", voice: "es-ES-ElviraNeural", description: "Castellano peninsular" },
  { id: "american", name: "Inglés Americano", country: "Estados Unidos", flag: "https://flagcdn.com/w40/us.png", color: "#B22234", locale: "en-US", voice: "en-US-ChristopherNeural", description: "Acento americano" },
  { id: "chilean", name: "Chileno", country: "Chile", flag: "https://flagcdn.com/w40/cl.png", color: "#D52B1E", locale: "es-CL", voice: "es-CL-LorenzoNeural", description: "Acento chileno" },
  { id: "venezuelan", name: "Venezolano", country: "Venezuela", flag: "https://flagcdn.com/w40/ve.png", color: "#CF142B", locale: "es-VE", voice: "es-VE-SebastianNeural", description: "Acento venezolano" },
  { id: "peruvian", name: "Peruano", country: "Perú", flag: "https://flagcdn.com/w40/pe.png", color: "#D91023", locale: "es-PE", voice: "es-PE-AlexNeural", description: "Acento limeño" },
  { id: "puertorican", name: "Boricua", country: "Puerto Rico", flag: "https://flagcdn.com/w40/pr.png", color: "#ED1C24", locale: "es-PR", voice: "es-PR-VictorNeural", description: "Acento puertorriqueño" },
  { id: "cuban", name: "Cubano", country: "Cuba", flag: "https://flagcdn.com/w40/cu.png", color: "#002A8F", locale: "es-CU", voice: "es-CU-ManuelNeural", description: "Acento cubano" },
  { id: "dominican", name: "Dominicano", country: "Rep. Dominicana", flag: "https://flagcdn.com/w40/do.png", color: "#002D62", locale: "es-DO", voice: "es-DO-RamonaNeural", description: "Acento dominicano" },
  { id: "portuguese", name: "Portugués", country: "Brasil", flag: "https://flagcdn.com/w40/br.png", color: "#009c3b", locale: "pt-BR", voice: "pt-BR-AntonioNeural", description: "Acento brasileño" },
  { id: "german", name: "Alemán", country: "Alemania", flag: "https://flagcdn.com/w40/de.png", color: "#FFCE00", locale: "de-DE", voice: "de-DE-ConradNeural", description: "Acento alemán" },
  { id: "italian", name: "Italiano", country: "Italia", flag: "https://flagcdn.com/w40/it.png", color: "#009246", locale: "it-IT", voice: "it-IT-DiegoNeural", description: "Acento italiano" },
  { id: "japanese", name: "Japonés", country: "Japón", flag: "https://flagcdn.com/w40/jp.png", color: "#BC002D", locale: "ja-JP", voice: "ja-JP-KeitaNeural", description: "Acento japonés" },
  { id: "french", name: "Francés", country: "Francia", flag: "https://flagcdn.com/w40/fr.png", color: "#002395", locale: "fr-FR", voice: "fr-FR-HenriNeural", description: "Acento francés" },
  { id: "british", name: "Inglés Británico", country: "Reino Unido", flag: "https://flagcdn.com/w40/gb.png", color: "#C8102E", locale: "en-GB", voice: "en-GB-RyanNeural", description: "Acento británico" },
  { id: "chinese", name: "Chino Mandarín", country: "China", flag: "https://flagcdn.com/w40/cn.png", color: "#EE1C25", locale: "zh-CN", voice: "zh-CN-XiaoxiaoNeural", description: "Acento chino" },
  { id: "arabic", name: "Árabe", country: "Arabia Saudita", flag: "https://flagcdn.com/w40/sa.png", color: "#006C35", locale: "ar-SA", voice: "ar-SA-HamedNeural", description: "Acento árabe" },
  { id: "hindi", name: "Hindi", country: "India", flag: "https://flagcdn.com/w40/in.png", color: "#FF9933", locale: "hi-IN", voice: "hi-IN-MadhurNeural", description: "Acento hindi" },
  { id: "russian", name: "Ruso", country: "Rusia", flag: "https://flagcdn.com/w40/ru.png", color: "#D52B1E", locale: "ru-RU", voice: "ru-RU-SvetlanaNeural", description: "Acento ruso" },
  { id: "australian", name: "Inglés Australiano", country: "Australia", flag: "https://flagcdn.com/w40/au.png", color: "#00008B", locale: "en-AU", voice: "en-AU-NatashaNeural", description: "Acento australiano" },
  { id: "indian_english", name: "Inglés Indio", country: "India", flag: "https://flagcdn.com/w40/in.png", color: "#FF9933", locale: "en-IN", voice: "en-IN-PrabhatNeural", description: "Acento inglés de India" },
  { id: "korean", name: "Coreano", country: "Corea del Sur", flag: "https://flagcdn.com/w40/kr.png", color: "#C60C30", locale: "ko-KR", voice: "ko-KR-SunHiNeural", description: "Acento coreano" },
  { id: "portuguese_eu", name: "Portugués Europeo", country: "Portugal", flag: "https://flagcdn.com/w40/pt.png", color: "#006600", locale: "pt-PT", voice: "pt-PT-DuarteNeural", description: "Acento portugués" },
  { id: "ecuadorian", name: "Ecuatoriano", country: "Ecuador", flag: "https://flagcdn.com/w40/ec.png", color: "#FFD100", locale: "es-EC", voice: "es-EC-LuisNeural", description: "Acento ecuatoriano" },
  { id: "uruguayan", name: "Uruguayo", country: "Uruguay", flag: "https://flagcdn.com/w40/uy.png", color: "#0038A8", locale: "es-UY", voice: "es-UY-MateoNeural", description: "Acento uruguayo" },
  { id: "english_normal", name: "Inglés (Normal)", country: "Internacional", flag: "https://flagcdn.com/w40/un.png", color: "#4B92DB", locale: "en-US", voice: "en-US-JennyNeural", description: "Acento inglés estándar" }
];
